"""Alert rule dataclass and enums.

Defines the schema for alert rules including severity levels, evaluation stages,
and condition types.
"""

from dataclasses import asdict, dataclass, fields
from enum import StrEnum
from typing import Any


class SeverityLevel(StrEnum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class EvaluationStage(StrEnum):
    """Data processing stages at which rules can be evaluated."""

    PROCESSED = "processed"


class ConditionType(StrEnum):
    """Types of alert conditions."""

    THRESHOLD = "threshold"
    RANGE = "range"
    DQ_SCORE = "dq_score"
    VALIDATION_FLAG = "validation_flag"


@dataclass
class AlertCondition:
    """Alert condition configuration.

    Attributes
    ----------
    type : ConditionType
        The type of condition to evaluate.
    **kwargs
        Additional condition-specific parameters (e.g., threshold, min_value, max_value).
    """

    type: ConditionType
    params: dict[str, Any]

    def __getattr__(self, name: str) -> Any:
        """Allow attribute-style access to params."""
        if name in self.params:
            return self.params[name]
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

    @classmethod
    def from_dict(cls, condition_data: dict[str, Any]) -> "AlertCondition":
        """Create AlertCondition from dictionary data."""
        condition_type_str = condition_data["type"]
        try:
            condition_type = ConditionType(condition_type_str)
        except ValueError:
            raise ValueError(
                f"Invalid condition type '{condition_type_str}'. Must be one of: "
                f"{', '.join(c.value for c in ConditionType)}"
            )

        params = {k: v for k, v in condition_data.items() if k != "type"}
        return cls(type=condition_type, params=params)


@dataclass
class AlertRule:
    """Alert rule configuration.

    Attributes
    ----------
    rule_id : str
        Unique identifier for the rule.
    name : str
        Human-readable name for the rule.
    description : str
        Description template with format placeholders.
    severity : SeverityLevel
        Severity level of alerts generated by this rule.
    evaluation_stage : EvaluationStage
        Data processing stage at which to evaluate this rule.
    source : str
        Sensor type or topic short name to apply rule to (use "*" for all).
    condition : AlertCondition
        Condition definition for triggering the alert.
    persistence_count : int
        Number of consecutive violations required before creating alert.
    cooldown_seconds : int
        Minimum seconds between alert firings for the same rule/source.
    """

    rule_id: str
    name: str
    description: str
    severity: SeverityLevel
    evaluation_stage: EvaluationStage
    source: str
    condition: AlertCondition
    persistence_count: int
    cooldown_seconds: int

    @classmethod
    def from_dict(cls, rule_data: dict[str, Any]) -> "AlertRule":
        """Create AlertRule from dictionary data."""

        # Check for missing fields
        required_fields = {f.name for f in fields(cls)}
        missing_fields = required_fields - rule_data.keys()
        if missing_fields:
            raise ValueError(f"Missing required fields for AlertRule: {missing_fields}")

        condition = AlertCondition.from_dict(rule_data["condition"])

        try:
            severity = SeverityLevel(rule_data["severity"])
        except ValueError:
            raise ValueError(
                f"Invalid severity '{rule_data['severity']}'. Must be one of: "
                f"{', '.join(s.value for s in SeverityLevel)}"
            )

        try:
            evaluation_stage = EvaluationStage(rule_data["evaluation_stage"])
        except ValueError:
            raise ValueError(
                f"Invalid evaluation stage '{rule_data['evaluation_stage']}'. Must be one of: "
                f"{', '.join(s.value for s in EvaluationStage)}"
            )

        return cls(
            rule_id=rule_data["rule_id"],
            name=rule_data["name"],
            description=rule_data["description"],
            severity=severity,
            evaluation_stage=evaluation_stage,
            source=rule_data["source"],
            condition=condition,
            persistence_count=rule_data["persistence_count"],
            cooldown_seconds=rule_data["cooldown_seconds"],
        )

    def override(self, override_data: dict[str, Any]) -> "AlertRule":
        """Create a new AlertRule with overridden parameters."""
        data = {
            "rule_id": override_data.get("rule_id", self.rule_id),
            "name": override_data.get("name", self.name),
            "description": override_data.get("description", self.description),
            "severity": (
                SeverityLevel(override_data["severity"])
                if "severity" in override_data
                else self.severity
            ),
            "evaluation_stage": (
                EvaluationStage(override_data["evaluation_stage"])
                if "evaluation_stage" in override_data
                else self.evaluation_stage
            ),
            "source": override_data.get("source", self.source),
            "condition": (
                AlertCondition.from_dict(override_data["condition"])
                if "condition" in override_data
                else self.condition
            ),
            "persistence_count": override_data.get("persistence_count", self.persistence_count),
            "cooldown_seconds": override_data.get("cooldown_seconds", self.cooldown_seconds),
        }
        return AlertRule(**data)

    def to_dict(self) -> dict[str, Any]:
        """Convert AlertRule to dictionary representation."""
        return asdict(self)
