#import "config.typ": *

#show: template

= Introduction 

#definition[Digital Twin][
    A *Digital Twin* is a system where data flows between an existing *physical object* and a *digital object*.
    The digital object act as a replica of the physical one which means that when a change is made in
    the physical object, it automatically changes the state of the digital object and vice versa.
]

#figure(
    image("img/dt_example.png", width: 70%),
    caption: [
        Digital Twin example @gao_dt
    ],
)


There are actually 3 levels of digital _twinning_ : 
+ *Digital Model*: The digital model is a system where the  data doesn't flow automatically between the physical object and the digital object.
    The changes made in the physical object are not reflected in the digital object and vice versa.
+ *Digital Shadow*: The digital shadow is a system where data flows authomatically from the physical object to the digital object.
   The digital object is a replica of the physical one but it doesn't send data back to the physical object (*e.g no actuators*) .
    This is the most basic form of digital twin and it is used to monitor the physical object.
+ *Digital Twin*: The digital twin is a system where data flows both ways between the physical object and the digital object.
    The digital object is a replica of the physical one and it can send data back to the physical object.
    This is the most advanced form of digital twin and it is used to monitor and control the physical object.

#figure(
    image("img/dt_levels.png", width: 60%),
    caption: [
        Levels of Digital Twin from https://vidyatec.com/blog/the-4-levels-of-the-digital-twin-technology/
    ],
)

Digital Twin's systems have the following characteristics:
- *Real-time*: The digital twin is able to receive data from the physical object in real-time using 
    IoT sensors i.e the data is sent to the digital object as soon as it is generated. In order 
    to dynamically change its state. 
- *Predictive*: The digital twin is able to predict the behavior of the physical object using machine learning algorithms. 
- *Autonomous*: The digital twin is able to make decisions and take actions on its own using AI algorithms based 
    on the data it processes.
- *Visualization*: One should be able to visualize the data and the behavior of the physical object using a graphical interface. 
    The user should also be able to interact with the digital twin using this graphical interface.
- ...


== Modeling

One important key feature of the Digital Twin is the notion of model.
The model is a representation of the physical object that is used to simulate its behavior and performance.
The model *doesn't need to be a perfect replica of the physical object*, but it should be able
to capture the key features and behaviors of the physical object.
In our case of a digital twin of a Plant, we will capture variables such as
temperature, soil moisture, humidity, light intensity or growth rate.

While the model need to be a good representation, it doesn't mean that it has to be complex.
The model needs to be as good as we are able to replace the physical object with the digital one
(in a limited context e.g temperature, humidity, etc.) and to be able to predict the behavior of the physical object
with good accuracy.

=== State Estimation

The state estimation is the process of estimating the state of the physical object using the data generated by the sensors.
In our case, the state of the physical object is a set of variables that describe the behavior and performance of the plant and its environment. 
We will represent the state of the digital twin using two sets of variables, 
one that represent *the state of the environment* ($E(t)$) and one that represent *the internal state of the plant* ($I(t)$)

We can define the state of the environement as $ E(t) = {L(t), M(t), T(t), H(t)} $ where:
- *Light Intensity*: Measured in lux, it is the amount of light that is received by the plant. 
    $L(t) in [0, 65000]$
- *Soil Moisture*: Measured in percentage, it is the amount of water that is present in the soil. 
    $M(t) in [0, 100]$
- *Temperature*: Measured in Celsius, it is the temperature of the environement of the plant.
    $T(t) in [-40, 80]$
- *Humidity*: Measured in percentage, it is the amount of water vapor that is present in the air. 
    $H(t) in [0, 100]$

The internal state of the plant is defined as $ I(t) = {G(t), C(t)} $ where: 
- *Growth Rate*: Measured in cm/day, it is the rate at which the plant is growing. 
    $G(t) in [0, 100]$ 
- *Global Coloring*: Measured in RGB, it is the color of the plant. 
    $C(t) in [0, 255]$  #highlight(fill: aqua)[Check if it is really relevant]

The state of the digital twin is then defined as $ S(t)$ as a function of the state of the environment and the internal state of the plant:
$ S(t) = f(E(t), I(t)) $




=== Decision Making


#bibliography("./bibliography.bib", full: true)
