"""Alert rule dataclass and enums.

Defines the schema for alert rules including severity levels, evaluation stages,
and condition types.
"""

import re
from dataclasses import MISSING, dataclass, fields
from datetime import datetime, time
from enum import StrEnum
from typing import Any

# TODO: Need to use serialization adapters


class SeverityLevel(StrEnum):
    """Alert severity levels."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class EvaluationStage(StrEnum):
    """Data processing stages at which rules can be evaluated."""

    PROCESSED = "processed"


class ConditionType(StrEnum):
    """Types of alert conditions."""

    THRESHOLD = "threshold"
    RANGE = "range"
    DQ_SCORE = "dq_score"
    VALIDATION_FLAG = "validation_flag"


@dataclass
class ActiveHours:
    """Local-time window during which a rule is active."""

    start: time
    end: time

    @classmethod
    def from_dict(cls, active_hours_data: dict[str, Any]) -> "ActiveHours":
        """Create ActiveHours from dictionary data."""
        if not isinstance(active_hours_data, dict):
            raise ValueError("Invalid active hours: expected mapping with start/end fields")

        try:
            start = cls._parse_time(active_hours_data["start"])
            end = cls._parse_time(active_hours_data["end"])
        except KeyError as exc:
            raise ValueError("Invalid active hours: missing start or end") from exc

        return cls(start=start, end=end)

    @staticmethod
    def _parse_time(value: Any) -> time:
        if not isinstance(value, str) or re.fullmatch(r"\d{2}:\d{2}", value) is None:
            raise ValueError("Invalid active hours: expected HH:MM format")

        try:
            return datetime.strptime(value, "%H:%M").time()
        except ValueError as exc:
            raise ValueError("Invalid active hours: expected HH:MM format") from exc


@dataclass
class AlertCondition:
    """Alert condition configuration.

    Attributes
    ----------
    type : ConditionType
        The type of condition to evaluate.
    **kwargs
        Additional condition-specific parameters (e.g., threshold, min_value, max_value).
    """

    type: ConditionType
    params: dict[str, Any]

    def __getattr__(self, name: str) -> Any:
        """Allow attribute-style access to params."""
        if name in self.params:
            return self.params[name]
        raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

    @classmethod
    def from_dict(cls, condition_data: dict[str, Any]) -> "AlertCondition":
        """Create AlertCondition from dictionary data."""
        # TODO: Use generic adapter with a special hook
        condition_type_str = condition_data["type"]
        try:
            condition_type = ConditionType(condition_type_str)
        except ValueError:
            raise ValueError(
                f"Invalid condition type '{condition_type_str}'. Must be one of: "
                f"{', '.join(c.value for c in ConditionType)}"
            )

        params = {k: v for k, v in condition_data.items() if k != "type"}
        return cls(type=condition_type, params=params)


@dataclass
class AlertRule:
    """Alert rule configuration.

    Attributes
    ----------
    rule_id : str
        Unique identifier for the rule.
    name : str
        Human-readable name for the rule.
    description : str
        Description template with format placeholders.
    severity : SeverityLevel
        Severity level of alerts generated by this rule.
    evaluation_stage : EvaluationStage
        Data processing stage at which to evaluate this rule.
    source : str
        Sensor type or topic short name to apply rule to (use "*" for all).
    condition : AlertCondition
        Condition definition for triggering the alert.
    active_hours : ActiveHours | None
        Optional local-time window during which the rule is active.
    persistence_count : int
        Number of consecutive violations required before creating alert.
    cooldown_seconds : int
        Minimum seconds between alert firings for the same rule/source.
    """

    rule_id: str
    name: str
    description: str
    severity: SeverityLevel
    evaluation_stage: EvaluationStage
    source: str
    condition: AlertCondition
    persistence_count: int
    cooldown_seconds: int
    active_hours: ActiveHours | None = None

    @classmethod
    def from_dict(cls, rule_data: dict[str, Any]) -> "AlertRule":
        """Create AlertRule from dictionary data."""
        # TODO: Use generic adapter with a special hook

        # Check for missing fields
        required_fields = {
            f.name for f in fields(cls) if f.default is MISSING and f.default_factory is MISSING
        }
        missing_fields = required_fields - rule_data.keys()
        if missing_fields:
            raise ValueError(f"Missing required fields for AlertRule: {missing_fields}")

        condition = AlertCondition.from_dict(rule_data["condition"])
        active_hours = (
            ActiveHours.from_dict(rule_data["active_hours"])
            if "active_hours" in rule_data
            else None
        )

        try:
            severity = SeverityLevel(rule_data["severity"])
        except ValueError:
            raise ValueError(
                f"Invalid severity '{rule_data['severity']}'. Must be one of: "
                f"{', '.join(s.value for s in SeverityLevel)}"
            )

        try:
            evaluation_stage = EvaluationStage(rule_data["evaluation_stage"])
        except ValueError:
            raise ValueError(
                f"Invalid evaluation stage '{rule_data['evaluation_stage']}'. Must be one of: "
                f"{', '.join(s.value for s in EvaluationStage)}"
            )

        return cls(
            rule_id=rule_data["rule_id"],
            name=rule_data["name"],
            description=rule_data["description"],
            severity=severity,
            evaluation_stage=evaluation_stage,
            source=rule_data["source"],
            condition=condition,
            persistence_count=rule_data["persistence_count"],
            cooldown_seconds=rule_data["cooldown_seconds"],
            active_hours=active_hours,
        )

    def override(self, override_data: dict[str, Any]) -> "AlertRule":
        """Create a new AlertRule with overridden parameters."""
        data = {
            "rule_id": override_data.get("rule_id", self.rule_id),
            "name": override_data.get("name", self.name),
            "description": override_data.get("description", self.description),
            "severity": (
                SeverityLevel(override_data["severity"])
                if "severity" in override_data
                else self.severity
            ),
            "evaluation_stage": (
                EvaluationStage(override_data["evaluation_stage"])
                if "evaluation_stage" in override_data
                else self.evaluation_stage
            ),
            "source": override_data.get("source", self.source),
            "condition": (
                AlertCondition.from_dict(override_data["condition"])
                if "condition" in override_data
                else self.condition
            ),
            "persistence_count": override_data.get("persistence_count", self.persistence_count),
            "cooldown_seconds": override_data.get("cooldown_seconds", self.cooldown_seconds),
            "active_hours": (
                ActiveHours.from_dict(override_data["active_hours"])
                if "active_hours" in override_data
                else self.active_hours
            ),
        }
        return AlertRule(**data)
